import os 
from datetime import datetime
from langchain_core.tools import tool

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")

@tool
def write_report(topic: str, search_results: str, rag_results: str = "") -> str:
    """Write a markdown research report from search and RAG results and save it to disk.
    Returns the report content as a string.
    """
    try:
        report = _build_report(topic, search_results, rag_results)
        _save_report(topic, report)
        return report
    
    except Exception as e:
        return f"Failed to write report: {str(e)}"
    

def _build_report(topic: str, search_results: str, rag_results: str) -> str:
    """Assemble the markdown report string."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    sections =  [
        f"# Research Report: {topic}",
        f"*Generated on {timestamp}*",
        "## Web Search Results",
        search_results if search_results else "No search results found.",
    ]

    if rag_results:
        sections += [
            "## Local Document Results",
            rag_results
        ]

    sections += [
        "result generated by agentic-research-assistant"
    ]

    return "\n\n".join(sections)

def _save_report(topic: str, report: str) -> None:
    """Save the report as a markdown file in the reports directory."""
    os.makedirs(REPORTS_DIR, exist_ok=True)
    
    filename = topic.lower().strip()
    filename = "".join(c if c.isalnum() or c == " "else "" for c in filename)
    filename = filename.replace(" ", "_")[:50]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    filepath = os.path.join(REPORTS_DIR, f"{filename}_{timestamp}.md")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"Report saved to: {filepath}")

# --- Test ---
if __name__ == "__main__":
    dummy_search = """dummy search result \n result 2"""
    result = write_report.invoke({"topic": "Test Topic", "search_results": dummy_search})
                                   
    print(result)
